<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0-windows</TargetFramework><AllowUnsafeBlocks>true</AllowUnsafeBlocks><UseWPF>true</UseWPF><UseWindowsForms>true</UseWindowsForms></PropertyGroup><ItemGroup><ProjectReference Include="..\Aurora.Desktop.Overlay.Core\Aurora.Desktop.Overlay.Core.csproj" /></ItemGroup><ItemGroup><EmbeddedResource Include="..\..\assets\ADO_icon.png" Link="Assets\ADO_icon.png" LogicalName="Aurora.Desktop.Overlay.Platform.Windows.Assets.ADO_icon.png" /></ItemGroup></Project>
